# Generated by Django 2.2.6 on 2019-11-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officecode', models.IntegerField()),
                ('officename', models.CharField(max_length=50)),
                ('attribution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationcode', models.IntegerField()),
                ('organizationname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('datejoined', models.DateTimeField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecode', models.IntegerField()),
                ('servicename', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('premium', models.BooleanField()),
                ('allocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestdate', models.DateTimeField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('motifofcancellation', models.TextField()),
                ('servicecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptiontypecode', models.IntegerField()),
                ('subscriptiontypename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('employername', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferfrom', models.CharField(max_length=50)),
                ('transferto', models.CharField(max_length=50)),
                ('requestdate', models.DateTimeField()),
                ('transferdate', models.DateTimeField()),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriptiontypecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubscriptionType'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('nativecountry', models.CharField(max_length=20)),
                ('citizenship', models.CharField(max_length=20)),
                ('isdelegate', models.CharField(max_length=20)),
                ('organizationcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Organization')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('officecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
    ]
