# Generated by Django 2.2.6 on 2019-11-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191113_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='servicecode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriptiontypecode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
